import { FLAVOR_MAP } from '../data/flavors.js'
import { getBatchCount } from '../utils/scale.js'
import { parseLocalDate } from '../utils/schedule.js'
import styles from './Manifest.module.css'

export default function Manifest({ order }) {
  const isPractice = order.mode === 'practice'
  const totalPints = order.flavors.reduce((s, f) => s + f.pints, 0)
  const totalBatches = isPractice
    ? order.flavors.length
    : order.flavors.reduce((s, { pints }) => s + getBatchCount(pints), 0)

  let pickupLabel   = '—'
  let readyByLabel  = '—'

  if (order.pickupDate) {
    const pickup = parseLocalDate(order.pickupDate)
    pickupLabel  = pickup.toLocaleDateString('en-US', {
      weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
    })
    const churn = new Date(pickup)
    churn.setDate(churn.getDate() - 1)
    readyByLabel = churn.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
  }

  return (
    <div className={styles.manifestWrap}>

      {/* ── Print button (hidden in print) ─────────────────────────── */}
      <div className={styles.printBar}>
        <button className={styles.printBtn} type="button" onClick={() => window.print()}>
          Print manifest
        </button>
      </div>

      {/* ── Printable document ────────────────────────────────────── */}
      <div className={styles.manifestDoc} data-manifest="">

        <header className={styles.manifestHeader}>
          <div className={styles.manifestBrand}>Chalo</div>
          <h1 className={styles.manifestTitle}>Production Manifest</h1>
          {isPractice ? (
            <p className={styles.manifestMeta}>Practice round</p>
          ) : order.pickupDate ? (
            <p className={styles.manifestMeta}>Pickup: {pickupLabel}</p>
          ) : null}
        </header>

        <table className={styles.manifestTable}>
          <thead>
            <tr>
              <th className={styles.thFlavor}>Flavor</th>
              <th className={styles.thNum}>Pints</th>
              <th className={styles.thNum}>Batches</th>
              <th className={styles.thNum}>Ready by</th>
            </tr>
          </thead>
          <tbody>
            {order.flavors.map(({ flavorId, pints }) => {
              const flavor  = FLAVOR_MAP[flavorId]
              const batches = isPractice ? 1 : getBatchCount(pints)
              return (
                <tr key={flavorId}>
                  <td className={styles.tdFlavor}>
                    <strong>{flavor.name}</strong>
                    <span className={styles.tdDescriptor}>{flavor.descriptor}</span>
                  </td>
                  <td className={styles.tdNum}>{isPractice ? '—' : pints}</td>
                  <td className={styles.tdNum}>{batches}</td>
                  <td className={styles.tdNum}>{isPractice ? '—' : readyByLabel}</td>
                </tr>
              )
            })}
          </tbody>
          <tfoot>
            <tr className={styles.totalRow}>
              <td className={styles.tdTotalLabel}>Total</td>
              <td className={styles.tdNum}>{isPractice ? '—' : totalPints}</td>
              <td className={styles.tdNum}>{totalBatches}</td>
              <td />
            </tr>
          </tfoot>
        </table>

        <footer className={styles.manifestFooter}>
          Generated by Chalo Production Tracker
        </footer>

      </div>
    </div>
  )
}
